defaults: &defaults
  images:
    sizes:
      small_avatar: "40x40"
      xsmall_avatar: "30x30"
      media_post: "80"
  roles:
    admin: "admin"
    recruiter: "recruiter"
  notifications:
    limit_show: 20
    notify_types:
      apply_job: "apply_job"
      share_post: "share_post"
      like: "like"
      post_feed: "post_feed"
      follow: "follow"
      feedback: "feedback"
  truncates:
    content_post_length: 150
  comments:
    limit: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
